[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py38"
exclude = ["pyinstrument/renderers/html_resources/app.js", "pyinstrument/vendor"]

[tool.ruff.lint]
select = ["I"]

[tool.pyright]
include = ["pyinstrument", "test"]
ignore = ["pyinstrument/vendor"]
pythonVersion = "3.8"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.pytest.ini_options]
addopts = "--ignore=test_cmdline.py --ignore=test/test_overflow.py --ignore=test/test_profiler_async.py --ignore=mutants --disable-warnings"
pythonpath = ["."]

[tool.mutmut]
source_paths = ["pyinstrument/"]
pytest_add_cli_args_test_selection = ["test/"]
